<?php

return array(
    '826' => __('United Kingdom', self::TEXT_DOMAIN),
    '036' => __('Australia', self::TEXT_DOMAIN),
    '040' => __('Austria', self::TEXT_DOMAIN),
    '056' => __('Belgium', self::TEXT_DOMAIN),
    '076' => __('Brazil', self::TEXT_DOMAIN),
    '124' => __('Canada', self::TEXT_DOMAIN),
    '156' => __('China', self::TEXT_DOMAIN),
    '203' => __('Czech Republic', self::TEXT_DOMAIN),
    '208' => __('Denmark', self::TEXT_DOMAIN),
    '250' => __('France', self::TEXT_DOMAIN),
    '276' => __('Germany', self::TEXT_DOMAIN),
    '344' => __('Hong Kong', self::TEXT_DOMAIN),
    '372' => __('Ireland', self::TEXT_DOMAIN),
    '380' => __('Italy', self::TEXT_DOMAIN),
    '392' => __('Japan', self::TEXT_DOMAIN),
    '410' => __('South Korea', self::TEXT_DOMAIN),
    '484' => __('Mexico', self::TEXT_DOMAIN),
    '528' => __('Netherlands', self::TEXT_DOMAIN),
    '578' => __('Norway', self::TEXT_DOMAIN),
    '620' => __('Portugal', self::TEXT_DOMAIN),
    '643' => __('Russia', self::TEXT_DOMAIN),
    '702' => __('Singapore', self::TEXT_DOMAIN),
    '724' => __('Spain', self::TEXT_DOMAIN),
    '752' => __('Sweden', self::TEXT_DOMAIN),
    '756' => __('Switzerland', self::TEXT_DOMAIN),
    '840' => __('United States', self::TEXT_DOMAIN),
    '858' => __('Uruguay', self::TEXT_DOMAIN)
);